### ISSUE TITLE
floating window doesn't show tracks on touchscreens

### ISSUE THREAD

**Issue by TheCubiq** [TheCubiq/vizzard#1]
when i unpin the bottom panel, the panel is slightly larger on touchscreens and so the little pointer is not on the screen
it is caused by 
```css
@media (pointer: coarse){
   .MuiSlider-root {
       padding: 20px 0;
   }
}
```
the volume slider gets then vertically a bit larger.
